agent_name: Embedding_rag_memoryos
model: deepseek-v3-2-251201
temperature: 1.0
input_length_limit: 10000000
buffer_length: 1000
output_dir: ./outputs/deepseek-chat-memoryos

retrieve_num: 10
short_term_capacity: 10
